name: Pull Request Reminders
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  review:
    runs-on: ubuntu-latest
    name: Notify Incoming New Pull Request
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: ./
        with:
          slack-webhook-url: ${{ secrets.PR_SLACK_WEBHOOK_URL }}
          pr-url: ${{ github.event.pull_request.html_url }}
          pr-reviewers: ${{ toJSON(github.event.pull_request.requested_reviewers) }}
          mapped-slack-user-id: ${{ secrets.SLACK_USER_IDS }}
        
